version = 1

[[annotations]]
path = [
    ".gitignore",
    ".github/workflows/reuse-compliance.yml",
]
SPDX-FileCopyrightText = "The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "layers/decompression/**",
    "docs/memory_decompression_layer.md",
]
SPDX-FileCopyrightText = ["The Khronos Group Inc.", "Nvidia Corporation"]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    ".github/dependabot.yml",
    "docs/shader_object_layer.md",
    "docs/synchronization2_layer.md",
]
SPDX-FileCopyrightText = "LunarG, Inc."
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = [
    "scripts/CMakeLists.txt",
    "layers/vk_layer_settings.txt",
    "layers/libVkLayer_khronos_synchronization2.map",
    "layers/json/VkLayer_khronos_synchronization2.json.in",
]
SPDX-FileCopyrightText = "LunarG, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/clang-format-diff.py"
SPDX-FileCopyrightText = "LLVM Project"
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"

[[annotations]]
path = [
    "layers/libVkLayer_khronos_memory_decompression.map",
    "layers/json/VkLayer_khronos_memory_decompression.json.in",
]
SPDX-FileCopyrightText = ["Nvidia Corporation"]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "layers/libVkLayer_khronos_timeline_semaphore.map",
    "layers/json/VkLayer_khronos_timeline_semaphore.json.in",
    "layers/vk_common.h",
    "layers/hash_table.cpp",
    "layers/hash_table.h",
    "layers/vk_util.h",
    "layers/vk_alloc.h",
    "layers/list.h",
    "layers/timeline_semaphore.c",
]
SPDX-FileCopyrightText = ["Intel"]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "layers/json/VkLayer_khronos_shader_object.json.in",
    "layers/libVkLayer_khronos_shader_object.map",
    "layers/vk_api_hash.h",
    "layers/shader_object/generated/.clang-format",
    "layers/VkLayer_khronos_shader_object.def",
    "layers/shader_object/shader_object_util.h",
    "layers/shader_object/shader_object_structs.h",
    "layers/shader_object/shader_object.cpp",
    "layers/shader_object/generated/**",
    "scripts/shader_object_generator.py",
    "tests/shader_object_tests.cpp",
    "tests/shader_object_tests.h",
]
SPDX-FileCopyrightText = "Nintendo"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    ".clang-format",
    "utils/generated/.clang-format",
    "utils/log.h",
    "utils/allocator.h",
    "utils/allocator.cpp",
]
SPDX-FileCopyrightText = ["LunarG, Inc.", "The Khronos Group Inc."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "tests/android/**",
    "tests/CMakeLists.txt",
    "scripts/github_ci_build_desktop.py",
    "scripts/android.py",
    "scripts/check_code_format.py",
    "scripts/known_good.json",
    "scripts/shader_object_data.json",
    ".github/workflows/format.yml",
    ".github/workflows/ci.yml",
]
SPDX-FileCopyrightText = ["Valve Corporation", "LunarG, Inc."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "CMakeLists.txt",
    "layers/CMakeLists.txt",
    "utils/CMakeLists.txt",
    "layers/VkLayer_khronos_synchronization2.def",
    "layers/VkLayer_khronos_timeline_semaphore.def",
]
SPDX-FileCopyrightText = ["Valve Corporation", "LunarG, Inc.", "Intel Corporation"]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "utils/cast_utils.h",
    "utils/vk_string_utils.h",
    "tests/test_common.h",
    "tests/vktestframework.h",
    "tests/vktestframework.cpp",
    "tests/vktestbinding.h",
    "tests/vktestbinding.cpp",
    "tests/test_environment.h",
    "tests/test_environment.cpp",
    "scripts/common_ci.py",
]
SPDX-FileCopyrightText = ["The Khronos Group Inc.", "Valve Corporation", "LunarG, Inc."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "layers/synchronization2.h",
    "layers/synchronization2.cpp"
]
SPDX-FileCopyrightText = ["The Khronos Group Inc.", "LunarG, Inc.", "Advanced Micro Devices, Inc."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "tests/vkrenderframework.h",
    "tests/vkrenderframework.cpp",
    "tests/synchronization2_tests.cpp",
    "tests/synchronization2_tests.h",
]
SPDX-FileCopyrightText = ["The Khronos Group Inc.", "Valve Corporation", "LunarG, Inc.", "Google, Inc."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/update_deps.py"
SPDX-FileCopyrightText = ["The Glslang Authors", "Valve Corporation", "LunarG, Inc.", "RasterGrid Kft."]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "tests/extension_layer_tests.cpp",
    "tests/extension_layer_tests.h",
]
SPDX-FileCopyrightText = ["The Khronos Group Inc.", "Valve Corporation", "LunarG, Inc.", "Google, Inc.", "Nvidia Corporation"]
SPDX-License-Identifier = "Apache-2.0"
